### PR TITLE
add golang

### PR DESCRIPTION
**Pull request by jonmcoe**
```
➜  ~ time curl http://localhost:8000/test/go/06798ce0cf734b1db5ab79f7f3870b92
{"result":true}
curl http://localhost:8000/test/go/06798ce0cf734b1db5ab79f7f3870b92  0.01s user 0.01s system 0% cpu 4.515 total
```

A little more copypasta than I'd like, but it works. 

Looked into doing the same for javascript. but it looks like a pretty hefty `package.json` is involved. I checked three assignments and it was identical - do you know if it's entirely uniform between projects? If so, that can go in the base image and it's not so bad. Having to wait on the `npm install` during the HTTP request, on the other hand, would be pretty rough

### CODE REVIEW

**Comment by zeerorg** [comment]
We need some tests in this. Apart from that everything looks nice.

**Comment by zeerorg** [comment]
Also javascript is a little trickier to figure out after ecmascript and javascript tracks were merged. My approach would be checking for presence of `package.json` file which indicates it is an ecmascript project and then running the test commands for ecmascript else running test commands for javascript.

**Comment by jonmcoe** [comment]
@zeerorg good idea, tests added. thanks for the background about the js

added test automation that can be seen here https://travis-ci.org/jonmcoe/exercism-test-runner/builds/426664276?utm_source=github_status&utm_medium=notification

**Comment by zeerorg** [comment]
No reason now why I shouldn't merge this. :-)

**Comment by zeerorg** [comment]
I also never knew add travis was this easy

**Comment by jonmcoe** [comment]
travis is wonderful and free for all public repos. big fan

**Pull request merged**
